name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        compiler: [gcc, clang]
        exclude:
          - os: windows-latest
            compiler: clang
          - os: macos-latest
            compiler: clang

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake build-essential

    - name: Set compiler
      run: echo "CC=${{ matrix.compiler }}" >> $GITHUB_ENV

    - name: Configure
      run: mkdir build && cd build && cmake ..

    - name: Build
      run: cd build && make

    - name: Test
      run: cd build && make test